### ISSUE TITLE
Survival settings/Sleep

### ISSUE THREAD

**Issue by SkathiLynOks** [davidou2a/HellRetex_Official#101]
**Describe the bug**
Playing the character it only take approx 15 mins for the sleep bar to go Red again after full rest.

**To Reproduce**
see description

**Expected behavior**two days ago it seemed to not work at all and there wa no need to sleep
**Screenshots/video**
N/a
**Server or Client (please complete the following information):**

 The issue is :
- On server side  

**Additional context**

**Comment by davidou2a** [comment]
https://github.com/davidou2a/HellRetex_Official/issues/100
