### ISSUE TITLE
Doors hoods trunks stopped breaking on iron

### ISSUE THREAD

**Issue by Akeador** [davidou2a/HellRetex_Official#105]
Actually everything is in the title of the topic

**Comment by Akeador** [comment]
Version 1.15

**Comment by davidou2a** [comment]
There is no related relation with our mods, this is not the Feedback tracker of Bohemia.
And your message is useless in this state, he give no information.
I close again this issue, if you re-post again an issue, take the time to think and explain the problem. if not you will be blocked.
