### ISSUE TITLE
Can't clean character in ponds etc

### ISSUE THREAD

**Issue by Schmorgus** [davidou2a/HellRetex_Official#106]
**Describe the bug**
There is no option at all to clean the character in ponds, or any other place.

**Expected behavior**
While in pond, cleanliness should improve (I assume) or get the option to "wash" the character.

**Server or Client (please complete the following information):**
 The issue is :
- both side

**Additional context**
I only use "HellRetex Enhanced Gameplay - Stable". No additional HellRetex mods.

**Comment by davidou2a** [comment]
There was never a way out of this, but can you describe how you do it?
- Which map?
- What actions do you perform?
- Maybe a video would be more clear

Thanks

**Comment by Schmorgus** [comment]
**Mods:** Image below.
**Map;** Chernarus Plus (original map).
**Actions:** Taking off all gear from character, walking down in "fresh" water (not the sea).

I don't have a video atm, but If it's still unclear, I might be able to make one.

![modlist](https://user-images.githubusercontent.com/22936310/146068083-70e4792e-5921-4435-8cb7-c83a34d3bd9b.jpg)

**Comment by davidou2a** [comment]
i bet you dont have completely read the doc...

![image](https://user-images.githubusercontent.com/1532436/146093686-e1fb4489-106c-4fc2-b10d-b1ec1447f623.png)

**Comment by Schmorgus** [comment]
But there's no action in the first place? O_o
Will investigate!

**Comment by davidou2a** [comment]
The action you see is Drink or Wash your hands if you have bloody hands, if you look better a little arrow is present, you should just scroll up or down with your mouse... and you can see the "Wash" action.

It's like that to avoid issues with limitations of DayZ.

**Comment by Schmorgus** [comment]
This is just hilarious.
2 days ago, I tried for hours to find this feature.
I had no option to scroll then (I know the small arrows).
Now, it just worked!
I assume some other mod was breaking it,
I had some other mods before which might still have been "active".
I cleaned the configs and everything after that session and now it was all fine.

I apologize for this pointless "bug" report.
