### ISSUE TITLE
Enhanced Gameplay is not compatable with Gear PDA

### ISSUE THREAD

**Issue by Gator1201** [davidou2a/HellRetex_Official#112]
**Describe the bug**
Enhanced Gameplay makes GearPDAs (https://steamcommunity.com/sharedfiles/filedetails/?id=2124309453&searchtext=gearpda) UI freeze when loaded. 

**To Reproduce**
If both mods are loaded with @CF, GearPDA UI will freeze. Player will have to hard exit the game once GearPDA's UI is opened.

**Expected behavior**
UI not freezing

**Screenshots/video**
If applicable, add screenshots/video to help explain your problem.

**Server or Client (please complete the following information):**
 The issue is :
- On client side

**Additional context**
I understand both are separate mods. They are both excellent and it would be awesome if both of these mods were able to work together. I also understand this is a convenience as GearPDA isn't your team's mod. I think the community would benefit from the compatibility.

**Comment by davidou2a** [comment]
Hello, need more informations like scripts.log crash.log and .RPT files when the issue occurs.

Thanks.

**Comment by davidou2a** [comment]
Issue lock since the athor haven't transmitted relevant informations.

**Comment by AfonsoBuarque** [comment]
sorted out?
