### ISSUE TITLE
sorry been busy 

### ISSUE THREAD

**Issue by bedrocmobb** [davidou2a/HellRetex_Official#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/video**
If applicable, add screenshots/video to help explain your problem.

**Server or Client (please complete the following information):**
 The issue is :
- On server side
- On client side
- both side

**Additional context**
[
![DayZ Screenshot 2021 11 02 - 02 54 28 10](https://user-images.githubusercontent.com/70449888/139799886-03d5d117-fe8a-49c7-be8e-e088e206fa9c.png)
](url)

**Comment by bedrocmobb** [comment]
that the bug i get

**Comment by davidou2a** [comment]
Please describe exactly what the problem is, when it occurs, what the normal behavior is, what mod it is...

I am not a guesser.

**Comment by bedrocmobb** [comment]
ok dont need to be rude and i i did explan it last time its when you click on the trader that screen stays and you have to logout cause the screen just stays there and you cant do shit

**Comment by bedrocmobb** [comment]
just forget it man i just wont use the mod not a big problem not the end of the world just trying to help out but seem like u dont like it so it i wont say anything more not going to try to help someone thats rude

**Comment by davidou2a** [comment]
Closed:
Author to lazy for post a good feedback.
