### ISSUE TITLE
HellRetex Enhanced Gamplay Tiredness System not working

### ISSUE THREAD

**Issue by SilverOcircle** [davidou2a/HellRetex_Official#99]
**Describe the bug**
Everything works with exception of the Tiredness System. The Icons is visible and it shows the arrows but the display does not change. I only run CF and HellRetex Enhanced Gameplay Mod..nothing else. There are also a few errors in my logs:

[crash_2021-11-04_14-42-32.log](https://github.com/davidou2a/HellRetex_Official/files/7475246/crash_2021-11-04_14-42-32.log)

[script_2021-11-04_14-42-32.log](https://github.com/davidou2a/HellRetex_Official/files/7475248/script_2021-11-04_14-42-32.log)

BTW: Your Mods are Great

**Comment by davidou2a** [comment]
Generally these kind of errors are related to a bad json, can you post your json server file?

**Comment by SilverOcircle** [comment]
Of course but i needed to convert it to a txt. because json isnt allowed.
[EnhancedGameplay_ServerSettings.txt](https://github.com/davidou2a/HellRetex_Official/files/7475775/EnhancedGameplay_ServerSettings.txt)

**Comment by davidou2a** [comment]
It's on a local server? or with COM in SinglePlayer ?

**Comment by SilverOcircle** [comment]
its on a nitrado server and also happens on a server from gtx gaming. i already used a validator for the json file.

**Comment by SilverOcircle** [comment]
this is the crash file from gtx. There are some more mods but the error is the same.
[crash_2021-11-04_19-59-37.log](https://github.com/davidou2a/HellRetex_Official/files/7479153/crash_2021-11-04_19-59-37.log)
We are on Chernarus but that shouldn't matter i think.

**Comment by davidou2a** [comment]
Hum, seems strange need more investigations, try to send me the .RPT maybe some informations are in.
Thanks

**Comment by el-PokoLoko** [comment]
Hello, good morning, I am very hooked on your mods, they are really a joy. but I am having the same problem that the friend above a couple of weeks ago the sleep system stopped working and I could never make it work "HeadgearConsumeRestrictionItems" and "MaskConsumeRestrictionItems" and I tried adding a single item to see if it was for the amount of items but not only those that come by default work. by the way my server is in GTX and I never had any problem.

Thank you very much for your work.

**Comment by SilverOcircle** [comment]
Here are the Log Files. I also updated the mod to the newest version but the problem is still around.
The Skill System works great and Dirtiness also. Before the update there were several crashs when reaching the time to earn a skill point. This is also gone with the newest version. But sleeping is still not doing anything. I testet different settings in the json. to see if there are issues. It feels like the settings for the sleeptimer is freezed or maybe hardcoded in your scripts. When you lay down to sleep the vision turns to black and the icon arrows show up...so it seems to work but the moon icon dosent change to yellow or red..it stays full all the time.

[script_2021-11-05_07-31-48(2).log](https://github.com/davidou2a/HellRetex_Official/files/7482306/script_2021-11-05_07-31-48.2.log
[DayZServer_x64_2021-11-05_07-31-43(2).txt](https://github.com/davidou2a/HellRetex_Official/files/7482307/DayZServer_x64_2021-11-05_07-31-43.2.txt)
)

**Comment by davidou2a** [comment]
i will try to summarize :
The tiredness work (arrow up and down) but you say the icon doesnt change?
have you try with a fresh spawn player ?

**Comment by SilverOcircle** [comment]
The tiredness work (arrow up and down) but you say the icon doesnt change?  - yes: arrows up and down are working and eye closing while lying works too. You only never get tired. Dosent matter how small you put the Number fpr tiredness in json.

have you try with a fresh spawn player ? yes, i also have tried a fresh installed and clean Server and Mission File.

**Comment by el-PokoLoko** [comment]
I also did everything you did, from creating a new server with only the mod and CF and deleting everything and starting from scratch now nothing is going for me, the minutes of the skills do not go down I think it is completely bugged B (

**Comment by SilverOcircle** [comment]
Dirtiness is good for me. The Skillsystem seems to work great and its normal that you have only the 3 first skills. They will implement more later.

**Comment by el-PokoLoko** [comment]
Thank you very much for clarifying my doubt. Hygiene has worked again but my sleep is still broken B (what a pity

**Comment by davidou2a** [comment]
i can't understand why that not works on your server...

https://www.youtube.com/watch?v=jagYZzWZSC0

On a fresh server it's ok and works... the problem seems not the mod. Dirtiness/Tiredness system was not changed since several months.
Actually there is not enough informations to help you, the mod work as intended, but not on your side, maybe something wrong but dont know what for the moment.

For SilverOcircle isn't a JSON problem, i have use your json for the test.

**Comment by el-PokoLoko** [comment]
but it happens to all the players on my server.
thanks for answering.

**Comment by SilverOcircle** [comment]
thank you davidou2a for your time. I will make some more tests hopefully i will figur out whats wrong. I will get back to you.

**Comment by el-PokoLoko** [comment]
it is worth if you can see what is the problem.
[script_2021-11-05_22-07-09[1].log](https://github.com/davidou2a/HellRetex_Official/files/7488939/script_2021-11-05_22-07-09.1.log)
[rpt.txt](https://github.com/davidou2a/HellRetex_Official/files/7488956/rpt.txt)

**Comment by davidou2a** [comment]
i suggest you add a semi-colon ";" after HREG - Stable in your -mod command line like following :
`@HellRetex Enhanced Gameplay - Stable;"`

When i see the bunch of errors in your scripts log two solutions :
- a massive conflict between one or multiple mods (try adding one by one to be sure)
- an error in a json file (not HREG json he is valid) or another file who ruins lot of things and cascade all errors in the stack

Check your server config each ; or " missed can broke all :)

**Comment by el-PokoLoko** [comment]
I perfectly understand. but I only tried the mod and @CF and it still doesn't work. I sent you this because on this server it worked perfectly with all these mods without any errors but I think it has been working for 2 1 week. but I appreciate your help I will try to delete everything for 2 times because this mod is essential for my server.

**Comment by SilverOcircle** [comment]
just a thought: is there a minimum value that must be entered in the .JSON?  For my last test, I write a “120” for tiredness and dirtyness.  if I understand the documentation correctly, then I should be jogging for 120 seconds in-game and the display should be blank.  correct?  Unfortunately, the display hadn't changed, and dirt hasn't changed, but what worked with a higher value before.  I'll do another test with the default settings of 4 hours for tiredness, but I haven't had the time.

**Comment by el-PokoLoko** [comment]
Hello very good, I have not had luck, I have spent the whole night trying and now it does not work anymore. Neither sleep nor hygiene and skills therefore all the players lost their B points (I don't know what to do and I deleted my server and started from scratch and still the error continues.

**Comment by davidou2a** [comment]
> 
> 
> just a thought: is there a minimum value that must be entered in the .JSON? For my last test, I write a “120” for tiredness and dirtyness. if I understand the documentation correctly, then I should be jogging for 120 seconds in-game and the display should be blank. correct? Unfortunately, the display hadn't changed, and dirt hasn't changed, but what worked with a higher value before. I'll do another test with the default settings of 4 hours for tiredness, but I haven't had the time.

The min is 3600 and the max is 86400 for 1h and 24h, if you put 3600 you should be red blinking status in ~1h if you jog only

**Comment by SilverOcircle** [comment]
"Never trust a user" this is funny! Thanks for clarification. After a few tests now i will give up. I installed a freshly new server with livonia and only cf and your mod as mods. I cleared all caches and settings and tiredness still dont work for me. The icon stays with a full filled moon and dosent change. the same thing happen in single player. what i noticed is that the little soap dispenser is never fully filled after fresh respawn. there is always a little missing. the moon is fully filled and stays on this condition. in your video the moon is already yellow. i have no idea anymore where to look at. 
Logs attache:
[crash_2021-11-06_13-35-24.log](https://github.com/davidou2a/HellRetex_Official/files/7490669/crash_2021-11-06_13-35-24.log)
[DayZServer_x64_2021-11-06_14-38-04.txt](https://github.com/davidou2a/HellRetex_Official/files/7490671/DayZServer_x64_2021-11-06_14-38-04.txt)
[script_2021-11-06_14-38-10.log](https://github.com/davidou2a/HellRetex_Official/files/7490672/script_2021-11-06_14-38-10.log)
![20211106155649_1](https://user-images.githubusercontent.com/6495698/140614147-328d4987-eafc-42b3-a3a6-a01040c8e7ae.jpg)

**Comment by el-PokoLoko** [comment]
I did the same for the third time, and the same thing happens to me.
and in your image it looks the same as my server, if you look there is a very fine line above the moon.

**Comment by davidou2a** [comment]
About Hygiene : You start never full, always between 60-75% it's intended
About SinglePlayer : This mod isnt designed for being used with COM or in SinglePlayer due to RPC.
About Nitrado : i dont use this shit and hoster like this (vilayer, gportal, Gtx...)

**Comment by SilverOcircle** [comment]
what would be your recommendation? Which Hoster do you prefer?

**Comment by el-PokoLoko** [comment]
OK, perfect. I can understand your frustration, but also understand ours that the mod worked perfectly and since the last two updates it did not. I'm not saying that your mod is broken or something like that, I was just looking for a solution to be able to enjoy it. but thank you very much anyway.

**Comment by davidou2a** [comment]
Dont worry, i'm not angry, or frustrated :)
I'dont say you lie :) i ask just more accurate informations for searching at the right side :)
FYI HellRetex Enhanced Gameplay it 56 000 lines of very complex code :)

I just need to know where i should search, now you say since 2-3 update the problem was come, and this is a good information for me, even if for you that seems not relevant, and now i have a possible idea where is the possible problem, just you do understand it's long and we have all a life :)

Just give me some time.

**Comment by davidou2a** [comment]
In example this one is ok for small servers :
https://contabo.com/en/storage-vps/vps-700/?image=windows-server.152&qty=1&contract=1

**Comment by davidou2a** [comment]
After reading lot of codes lines changes in 3 last update of Stable i have found this : 

![Sans titre](https://user-images.githubusercontent.com/1532436/140626596-9e599902-785b-46cf-b9ac-5afce9432405.png)

The max value of Tiredness like Dirtyness is 1000, i have just put a 0 in more that explain the issue in Stable version.

**Comment by SilverOcircle** [comment]
thank you for taking the time to check everything again.  thank you that the update is already online and I will follow your tip with the hosters.  I am convinced that you are much more flexible with your solution than with those from nitrado etc. unfortunately I also lack a bit of programming knowledge.  BTW are you from Germany?

**Comment by davidou2a** [comment]
I'm not German :) just the country near, France.
But this hoster is the best solution i have found for my server : small community and a dedicated host :)
To deploy a server on this type of VPS you dont need huge knowledgements, just how to use a RDP Client to connect on the server, and just install OmegaManager from CFTools (you can use for free or with a paid solution) or similar Server Manager :) nothing very complicated :)

https://www.reddit.com/r/CFTools/comments/a9orll/omegamanager/
https://www.windowscentral.com/how-use-remove-desktop-app-connect-pc-windows-10-0

**Comment by Boyscout018** [comment]
Hello! depuis qu'il ya eu la mise a jour, mes joueurs  sont fatigués tres rapidement et ça devient tres vite infecte niveau jouabilité. je cherche à les faire dormir tous les 1 jour et demi et se laver tous les 2 jours mais les parametres que je mets dans le Json ne changent rien...du coup j'ai desinstallé  le mod!!! idem pour plusieurs potes qui ont un serveur...Dommage car je trouvais ce mod tres bien et il fonctionnait tres bien.

**Comment by davidou2a** [comment]
Ici c'est un feedback tracker pas le bureau des pleurs.
- Désinstalles le mod si il ne te convient pas.
- Si tu avais lu la doc tu aurais les réponses à tes questions
- Il fonctionne toujours très bien, mais visiblement il ne te convient pas

Sur ce bonne route.
